:stem: latexmath

=== 湿度計算のバランス式

==== 1. 概要

室の湿度バランス式を連立させて、次時刻の室の湿度を計算する式を導出する。

==== 2. 記号説明

[cols="^.^1,<.^7", stripes=none, options="header"]
|===

^.^| 記号
^.^| 説明

| stem:[\rho_a] | 空気の密度, kg/m^3^

| stem:[V_{room}]
| 室stem:[i]の容積, m^3^ +
stem:[\begin{pmatrix}
  V_{room,0} \\
  \vdots \\
  V_{room, i-1}
\end{pmatrix}]
で表されるベクトル

| stem:[X_{r,n}]
| ステップ stem:[ n ] における室stem:[i]の絶対湿度, kg/kg(DA) +
stem:[\begin{pmatrix}
  X_{r,0,n} \\
  \vdots \\
  X_{r,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[ t ] | 時間, s

| stem:[V_{out,vent,n}]
| ステップ stem:[n]における室stem:[i]の外からの換気量, m^3^/s +
（機械換気量・すきま風量・自然風利用時の換気量との合計である。） +
stem:[\begin{pmatrix}
  V_{out,vent,0,n} \\
  \vdots \\
  V_{out,vent,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[X_{o,n}]
| ステップ stem:[n] における外気絶対湿度, kg/kg(DA) +
stem:[\begin{pmatrix}
  X_{o,0,n} \\
  \vdots \\
  X_{o,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[X_{gen,n}]
| ステップ stem:[n] の室 stem:[i] における人体発湿を除く内部発湿, kg/s +
stem:[\begin{pmatrix}
  X_{gen,0,n} \\
  \vdots \\
  X_{gen,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[X_{hum,n}]
| ステップ stem:[n] の室 stem:[i] における人体発湿, kg/s +
stem:[\begin{pmatrix}
  X_{hum,0,n} \\
  \vdots \\
  X_{hum,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[X_{frt,n}]
| ステップ stem:[n] の室 stem:[i] における家具等の絶対湿度, kg/kg(DA) +
stem:[\begin{pmatrix}
  X_{frt,0,n} \\
  \vdots \\
  X_{frt,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[C_{cap,w,frt}]
| 室 stem:[i] の家具等の湿気容量, kg/(kg/kg(DA)) +
stem:[\begin{pmatrix}
  C_{cap,w,frt,0} \\
  \vdots \\
  C_{cap,w,frt,i-1} \\
\end{pmatrix}]
で表されるベクトル

| stem:[C_{w,frt}]
| 室 stem:[i] の家具等と空気間の湿気コンダクタンス, kg/(s kg/kg(DA)) +
stem:[\begin{pmatrix}
  C_{w,frt,0} \\
  \vdots \\
  C_{w,frt,i-1}
\end{pmatrix}]
で表されるベクトル

| stem:[V_{int,vent,n}]
| ステップ stem:[n] の隣室 stem:[i] から室 stem:[i] への機械換気量, m^3^/s +
stem:[\begin{pmatrix}
  V_{int,vent,0,0,n} & \ldots & V_{int,vent,0,i-1,n} \\
  \vdots & \ddots & \vdots \\
  V_{int,vent,i-1,0,n} & \ldots & V_{int,vent,i-1,i-1,n}
\end{pmatrix}]
で表されるベクトル

| stem:[ G_{RAC,n} ] | ステップ stem:[n] における室 stem:[i] に設置されたルームエアコンディショナーの除湿量, kg/s

| stem:[ V_{ac} ] | 空調風量, m^3^/s
| stem:[ BF ] | バイパスファクター
| stem:[ xe_{out,n} ] | ステップ stem:[ n ] におけるルームエアコンディショナー室内機熱交換器表面における飽和絶対湿度, kg/kg(DA)

|===

==== 2. 室空気の水分収支

室空気の水分収支は式(1)で表される。

[stem]
++++
\rho_a \: V_{room} \otimes \frac{dX_r}{dt} = \rho_a \: V_{out,vent} \otimes (X_{o} - X_{r}) + X_{gen} + X_{hum} - G_{RAC} + C_{w,frt} \otimes (X_{frt} - X_{r}) + \rho_a \: V_{int,vent} \: X_{r} \tag{1}
++++

空調除湿量はルームエアコンの場合式(2)で表される。

[stem]
++++
G_{RAC} = \left\{ \begin{array}{ll}
  \rho_a \: V_{RAC} \: (1 - BF_{RAC}) \: (X_{r} - X_{RAC,ex}) & (X_r \gt X_{RAC,ex})\\
  0.0 & (X_r \le X_{RAC,ex})
\end{array} \right. \tag{2}
++++

備品の水分収支式は室空気との物質移動だけを考慮すればよいため、次式で表すことができる。

[stem]
++++
C_{cap,w,frt} \otimes \frac{dX_{frt,n}}{dt} = C_{w,frt} \otimes (X_r - X_{frt}) \tag{3}
++++

式(1)～式(3)を後退差分で離散化すると以下のようになる。

[stem]
++++
\begin{split}
\rho_a \: V_{room} \otimes \frac{X_{r,n+1} - {X_{r,n}}}{\Delta t} &= \rho_a \: V_{out,vent,n} \otimes (X_{o,n+1} - X_{r,n+1}) \\
&+ X_{gen,n} + X_{hum,n} \\
&- G_{RAC,n} \\
&+ C_{w,frt} \otimes (X_{frt,n+1} - X_{r,n+1}) \\
&+ \rho_a \: V_{int,vent,n} \: X_{r,n+1}
\end{split} \tag{4}
++++

[stem]
++++
G_{RAC,n} = \left\{ \begin{array}{ll}
  \rho_a \: V_{RAC,n} \: (1 - BF_{RAC}) \: (X_{r,n+1} - X_{RAC,ex,n+1}) & (X_{r,n+1} \gt X_{RAC,ex,n+1})\\
  0.0 & (X_{r,n+1} \le X_{RAC,ex,n+1})
\end{array} \right. \tag{5}
++++

[stem]
++++
C_{cap,w,frt} \otimes \frac{X_{frt,n+1} - X_{frt,n}}{\Delta t} = C_{w,frt} \otimes (X_{r,n+1} - X_{frt,n+1}) \tag{6}
++++

式(6)を stem:[X_{frt,n+1}] について解くと次式となる。

[stem]
++++
X_{frt,n+1} = (\Delta t \: C_{w,frt} \otimes X_{r,n+1} + C_{cap,w,frt} \otimes X_{frt,n}) \otimes (C_{cap,w,frt} + \Delta t \: C_{w,frt})^{-1} \tag{7}
++++

この式および式(5)を式(4)に代入する。

[stem]
++++
\begin{split}
\rho_a \: V_{room} \otimes \frac{X_{r,n+1} - {X_{r,n}}}{\Delta t} &= \rho_a \: V_{out,vent,n} \otimes (X_{o,n+1} - X_{r,n+1}) \\
&+ X_{gen,n} + X_{hum,n} \\
&- \left\{ \begin{array}{ll}
  \rho_a \: V_{RAC,n} \: (1 - BF_{RAC}) \: (X_{r,n+1} - X_{RAC,ex,n+1}) & (X_{r,n+1} \gt X_{RAC,ex,n+1})\\
  0.0 & (X_{r,n+1} \le X_{RAC,ex,n+1})
\end{array} \right. \\
&+ C_{w,frt} \otimes C_{cap,w,frt} \otimes (X_{frt,n} - X_{r,n+1}) \otimes (C_{cap,w,frt} + \Delta t \: C_{w,frt})^{-1} \\
&+ \rho_a \: V_{int,vent,n} \: X_{r,n+1}
\end{split} \tag{8}
++++

この式を stem:[X_{r,n+1}] について解くと以下の式となる。

[stem]
++++
BRMX \: X_{r,n+1} = BRMC
++++

ここで、

（除湿しない場合）

[stem]
++++
\begin{split}
BRMX_{not-dh} &= \rho_{a} \: \left( diag \left( \frac{V_{room}}{\Delta t} + V_{out,vent,n} \right) - V_{int,vent,n} \right) \\
&+ diag \left( C_{w,frt} \otimes C_{cap,w,frt} \otimes (C_{cap,w,frt} + \Delta t C_{w,frt})^{-1} \right)
\end{split} \tag{8}
++++

[stem]
++++
\begin{split}
BRMC_{not-dh} &= \rho_{a} \: \left( \frac{V_{room}}{\Delta t} \otimes X_{r,n} + V_{out,vent,n} \otimes X_{o,n+1} \right) \\
&+ X_{gen,n} + X_{hum,n} \\
&+ C_{w,frt} \otimes C_{cap,w,frt} \otimes X_{frt,n} \otimes (C_{cap,w,frt} + \Delta t C_{w,frt})^{-1}
\end{split} \tag{9}
++++

（除湿する場合）

[stem]
++++
BRMX_{dh} = BRMX_{not-dh} + \rho_{a} \: V_{RAC,n} \: (1 - BF_{RAC})
++++

[stem]
++++
BRMC_{dh} = BRMC_{not-dh} + \rho_{a} \: V_{RAC,n} \: (1 - BR_{RAC}) \: X_{RAC,ex,n+1}
++++

ここで、除湿するかしないかの判断は stem:[n+1] における絶対湿度に依存する。ここで除湿の有無が除湿をするか否かの判断の閾値を超えることがない（除湿無しで計算した結果、除湿ありの条件に入り、除湿ありで計算した結果、除湿なしの条件に入るような、ある種、振動するような玄象が生じない）ため、一度、除湿無しで計算をし、計算された絶対湿度から除湿の有無を判断することができる。
