image: python:3.7
pipelines:
  default:
    - step:
        script:
          # Show versions
          - python --version
          # Install depencencies
          - pip install numpy matplotlib IPython nbformat nbimporter
          # Run tests
          - cd convert && python -m unittest discover -p "test*.py"
