image: python:3.5
pipelines:
  default:
    - step:
        script:
          # Show versions
          - python --version
          # Install depencencies
          - pip install numpy matplotlib IPython nbformat nbimporter
          # Run tests
          - python -m unittest discover -p "Test*.py"
          - cd headload_calc && python -m unittest discover -p "Test*.py"

