== B. 室用途が指定されていない場合の外皮の部位の室用途とそれに接する面積の推定

　外皮の部位が接する室の用途が指定されていない場合、その外皮の部位1つを、「主たる居室」「その他の居室」「非居室」の3つの部位に分けることとし、面積については式(1)、長さについては式(2)による。なお、外皮の部位の種類・隣接空間の種類・方位、その他の仕様については、3つの部位すべてもとの部位と同じとする。

外皮の部位が一般部位・開口部の場合の面積

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
A_{evlp,mr,i} = \frac{A_{f,mr}}{A_{f,total}} A_{evlp,i} \tag{1a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
A_{evlp,or,i} = \frac{A_{f,or}}{A_{f,total}} A_{evlp,i} \tag{1b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
A_{evlp,nr,i} = \frac{A_{f,total} - A_{f,mr} - A_{f,or}}{A_{f,total}} A_{evlp,i} \tag{1c}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

外皮の部位が熱橋の場合の長さ

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
l_{evlp,mr,i} = \frac{A_{f,mr}}{A_{f,total}} l_{evlp,i} \tag{2a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
l_{evlp,or,i} = \frac{A_{f,or}}{A_{f,total}} l_{evlp,i} \tag{2b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
l_{evlp,nr,i} = \frac{A_{f,total} - A_{f,mr} - A_{f,or}}{A_{f,total}} l_{evlp,i} \tag{2c}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

　ここで、 +
　stem:[A_{evlp,mr,i}]：主たる居室に接する外皮の部位（一般部位・開口部）stem:[i]の面積, m^2^ +
　stem:[A_{evlp,or,i}]：その他の居室に接する外皮の部位（一般部位・開口部）stem:[i]の面積, m^2^ +
　stem:[A_{evlp,nr,i}]：非居室に接する外皮の部位（一般部位・開口部）stem:[i]の面積, m^2^ +
　stem:[A_{evlp,i}]：外皮の部位（一般部位・開口部）stem:[i]の面積, m^2^ +
　stem:[l_{evlp,mr,i}]：主たる居室に接する外皮の部位（熱橋）stem:[i]の長さ, m +
　stem:[l_{evlp,or,i}]：その他の居室に接する外皮の部位（熱橋）stem:[i]の長さ, m +
　stem:[l_{evlp,nr,i}]：非居室に接する外皮の部位（熱橋）stem:[i]の長さ, m +
　stem:[l_{evlp,i}]：外皮の部位（熱橋）stem:[i]の長さ, m +
　stem:[A_{f,total}]：床面積の合計, m^2^ +
　stem:[A_{f,mr}]：主たる居室の床面積, m^2^ +
　stem:[A_{f,or}]：その他の居室の床面積, m^2^ +
である。

　土間床等の外周部及び土間床等の中心部が接する空間は、すべて、「床下空間」とする。
