=== X.5 太陽位置

==== X.5.1 概要

　太陽高度と太陽方位角を計算する。

==== X.5.2 均時差と赤緯

　均時差と赤緯は、式(1)から式(7)による。

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
n = Y - 1968 \tag{1}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
d_0 = 3.71 + 0.2596 n - INT \left[ \frac{n+3}{4} \right] \tag{2}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
M = 2 \pi \cdot \frac{(D-d_0)}{D_{ay}} \tag{3}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\epsilon = \frac{2 \pi}{360} \cdot \left( 12.3901 + 0.0172 \cdot \left( n + \frac{M}{2 \pi} \right) \right) \tag{4}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
v = M + \frac{2 \pi}{360} \cdot \left( 1.914 \cdot \sin{M} + 0.02 \cdot \sin{(2M)} \right) \tag{5}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
E_t = (M - v) - \tan^{-1} \left( \frac{ 0.043 \cdot \sin {2( v + \epsilon )} }{ 1 - 0.043 \cdot \cos {2(v + \epsilon)} } \right) \tag{6}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\sin{\delta} = \cos{(v+\epsilon)} \cdot \sin{\delta_0} \tag{7a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\cos{\delta} = \sqrt{1 - \sin^2{\delta}} \tag{7b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

stem:[$INT$] は小数点以下切り捨てた整数を表す。

　ここで、 +
　stem:[n]：1968年との年差 +
　stem:[Y]：西暦年(=1989) +
　stem:[d_0]：平均軌道上の近日点通過日（暦表時による1968年1月1日正午基準の日差）, d +
　stem:[M]：平均近点離角, rad +
　stem:[D]：年通算日（1/1を stem:[D=1] とする), d +
　stem:[D_{ay}]：近点年（近日点基準の公転周期日数）(=365.2596), d +
　stem:[\epsilon]：近日点と冬至点の角度, rad +
　stem:[v]：真近点離角, rad +
　stem:[E_t]：均時差, rad +
　stem:[\delta]：赤緯, rad +
　stem:[\delta_0]：北半球の冬至の日赤緯(=-23.4393[deg]), deg +
である。

==== X.5.3 時角

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
t = 2 \pi \cdot \frac{T_m - 12}{24} + (L - L_0) + E_t \tag{8}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

ここで、 +
　stem:[t]：時角, rad +
　stem:[T_m]：標準時, h +
　stem:[L]：経度, rad +
　stem:[L_0]：標準時の地点の経度（標準子午線）, rad +
　stem:[E_t]：均時差, rad +
である。


==== X.5.4 太陽位置

　太陽高度 stem:[h_s] は式(9)、太陽方位角 stem:[A_s] は式(10)による。

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\sin{h_s} = \max{ \left( 0, \sin{\phi} \sin{\delta}⁡ + \cos{\phi} \cos{\delta}⁡ \cos{t} \right) ⁡} \tag{9a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\cos{h_s} = \sqrt{1 - \sin^2{h_s}} \tag{9b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\sin A_s = \left\{ \begin{array}{ll}
  \frac{ \cos \delta \sin t }{ \cos h_s } & ( h_s \gt 0 ) \\
  0 & ( h_s = 0 )
\end{array} \right.
\tag{10a}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\cos A_s = \left\{ \begin{array}{ll}
  \frac { \sin h_s \sin \phi - \sin \delta }{ \cos h_s \cos \phi } & ( h_s \gt 0 ) \\
  0 & ( h_s = 0 )
\end{array} \right.
\tag{10b}
++++++++++++++++++++++++++++++++++++++++++++

ここで、 +
　stem:[h_s]：太陽高度, rad +
　stem:[A_s]：太陽方位角, rad +
　stem:[\phi]：緯度, rad +
　stem:[\delta]：赤緯, rad +
　stem:[t]：時角, rad +
である。
