:stem: latexmath

== 湿度の計算

=== I. 評価法

==== 1. 室全体の水分収支

　ステップ stem:[n+1] における室 stem:[i] の絶対湿度 stem:[X_{r,i,n+1}] 及びステップ stem:[n] からステップ stem:[n+1] における
室 stem:[i] の潜熱負荷（加湿を正・除湿を負とする） stem:[\hat{L}_{L,i,n}] を求めるにあたり以下の2種類の方法を設ける。 +
　A法：目標とする絶対湿度を設定する方法 +
　B法：除湿・加湿量を設定する方法（除湿量・加湿量がゼロの場合も含む） +
　C法：除湿量を室内の絶対湿度に応じて設定する方法 +
　本項では、A法・B法・C法ごとに、ステップn+1における室の絶対湿度と潜熱負荷の計算方法を示し、その次に、3つの方法共通の計算式を記す。


=== II. 根拠

　室空気の水分収支は式(1)で表される。

[stem]
++++
\begin{split}
\rho_a \cdot V_{room,i} \cdot \frac{dX_{r,i}}{dt}
&= \rho_a \dot V_{out,vent,i} \dot ( X_o - X_{r,i} ) \\
&+ G_{lh,frt,i} \cdot ( X_{frt,i} - X_{r,i} ) \\
&+ \rho_a \sum_j^{J-1}{V_{int,vent,i,j} \cdot (X_{r,j} - X_{r,i})} \\
&+ X_{gen,i} + X_{hum,i} + L_{L,i}
\end{split} \tag{b1}
++++

　ここで、 +
　stem:[ρ_a]：空気の密度, kg/m^3^ +
　stem:[V_{room,i}]：室stem:[i]の容積, m^3^ +
　stem:[X_{r,i}]：室stem:[i]の絶対湿度, kg/kg(DA) +
　stem:[X_{r,j}]：室jの絶対湿度, kg/kg(DA) +
　stem:[t]：時間, s +
　stem:[V_{out,vent,i}]：室stem:[i]の外気との換気量, m^3^/s +
　stem:[X_o]：外気絶対湿度, kg/kg(DA) +
　stem:[G_{lh,frt,i}]：室stem:[i]の家具等と空気間の湿気コンダクタンス, kg/(s kg/kg(DA)) +
　stem:[X_{frt,i}]：室stem:[i]の家具等の絶対湿度, kg/kg(DA) +
　stem:[V_{int,vent,i,j}]：室stem:[j]から室stem:[i]への機械換気量, m^3^/s +
　stem:[X_{gen,i}]：室stem:[i]の人体発湿を除く内部発湿, kg/s +
　stem:[X_{hum,i}]：室stem:[i]の人体発湿, kg/s +
　stem:[L_{L,i}]：室stem:[i]の潜熱負荷（加湿を正・除湿を負とする）, kg/s +
である。 +
　空調による除湿・加湿の方法として以下のパターンを想定した。 +
・ 除湿・加湿を行わない場合 +
・ （加湿器の使用など）固定値で除湿・加湿を行う場合 +
・ 目標絶対湿度を満たすように除湿・加湿を行う場合（従来の負荷計算方法） +
・ 室内の絶対湿度に応じて除湿量が定まる場合（放射パネルやエアコンなど除湿量を完全には制御しない方式）

　これらを踏まえて、一般的に室 stem:[i] の潜熱負荷 stem:[L_{L,i}] を以下の式で表す。

[stem]
++++
L_{L,i} = L_{a,i} \cdot X_{r,i} + L_{b,i}
\tag{b2}
++++

　除湿・加湿を行わない場合、 stem:[L_{a,i} = 0] 及び stem:[L_{b,i} = 0] とすればよい。 +
　固定値で除湿・加湿を行う場合、 stem:[L_{a,i} = 0] とし、与えたい除湿・加湿量を stem:[L_{b,i}] に与えれば良い。 +
　目標絶対湿度を満たすように除湿・加湿を行う場合、 stem:[L_{a,i} = 0] としたうえで、 stem:[L_{b,i}] を未知数として除湿・加湿量を求めれば良い。 +
　室内の絶対湿度に応じて除湿を行う方法の場合、室内の絶対湿度と除湿を行う表面の飽和絶対湿度との差によって除湿量が決定される場合が多い。その場合、以下のような式で表される。

[stem]
++++
L_{L,i} = \left\{ \begin{array}{ll}
  -k_{l,i} \cdot (X_{r,i} - X_{srf,ex,i}) & ( X_{r,i} \gt X_{srf,ex,i} ) \\
  0 & ( X_{srf,ex,i} \le X_{r,i} )
\end{array} \right.
\tag{b3}
++++

　ここで、 +
　stem:[X_{srf,ex,i}]：室stem:[i]に設置された設備の熱交換器表面の飽和絶対湿度, kg/kg(DA) +
　stem:[k_{l,i}]：室stem:[i]に設置された設備の熱交換器表面の湿気コンダクタンス, kg/(s kg/kg(DA)) +
である。 +
　このように、絶対湿度と熱交換器表面における飽和絶対湿度との大小関係によって除湿の有無が決定されるため、
数値計算においては、一旦、除湿を行わない場合の絶対湿度 stem:[X_{r,ndh,i}] を求め、
その湿度と熱交換器表面における飽和絶対湿度 stem:[ X_{srf,ex,i}] の大小を比較して除湿量を決定することになる。
stem:[L_{a,i}] 及び stem:[L_{b,i}] の決定方法は後述する。

　備品の水分収支式は室空気との物質移動だけを考慮すればよいため、次式で表すことができる。

[stem]
++++
C_{lh,frt,i} \cdot \frac{dX_{frt,i}}{dt} = G_{lh,frt} \cdot ( X_{r,i} - X_{frt,i} )
\tag{b4}
++++

　ここで、 +
　stem:[C_{lh,frt,i}]：室stem:[i]の家具等の湿気容量, kg/(kg/kg(DA)) +
である。 +
　式(b2)を式(b1)に代入して後退差分で離散化すると次式となる。

[stem]
++++
\begin{split}
\rho_a \cdot V_{room,i} \cdot \frac{ X_{r,i,n+1} - X_{r,i,n} }{ \Delta t }
&= \rho_a \cdot \hat{V}_{out,vent,i,n} \cdot ( X_{o,n+1} - X_{r,i,n+1} ) \\
&+ G_{lh,frt,i} \cdot ( X_{frt,i,n+1} - X_{r,i,n+1} ) \\
&+ \rho_a \cdot \sum_j^{J-1}{\hat{V}_{int,vent,i,j,n} \cdot ( X_{r,j,n+1} - X_{r,i,n+1} ) } \\
&+ \hat{X}_{gen,i,n} + \hat{X}_{hum,i,n} + \hat{L}_{a,i,n} \cdot X_{r,i,n+1} + \hat{L}_{b,i,n}
\end{split}
\tag{b5}
++++

　ここで、記号の上につく横線（ハット）は、ステップ stem:[n] から stem:[n+1] の期間における積算値または平均値を表す。 +
　stem:[\Delta t]：1ステップの時間間隔, s +
　stem:[X_{r,i,n)}]：ステップ stem:[n] における室iの絶対湿度, kg/kg(DA) +
　stem:[X_{r,j,n}]：ステップ stem:[n] における室jの絶対湿度, kg/kg(DA) +
　stem:[\hat{V}_{out,vent,i,n}]：ステップ stem:[n] からステップ stem:[n+1] における室 stem:[i] の外気との換気量, m^3^/s +
　stem:[X_{o,n}]：ステップ stem:[n] における外気絶対湿度, kg/kg(DA) +
　stem:[X_{frt,i,n}]：ステップ stem:[n] における室 stem:[i] の家具等の絶対湿度, kg/kg(DA) +
　stem:[\hat{V}_{int,vent,i,j,n}]：ステップ stem:[n] からステップ stem:[n+1] における室 stem:[j] から室iへの機械換気量, m^3^/s +
　stem:[\hat{X}_{gen,i,n}]：ステップ stem:[n] における室 stem:[i] の人体発湿を除く内部発湿, kg/s +
　stem:[\hat{X}_{hum,i,n}]：ステップ stem:[n] における室 stem:[i] の人体発湿, kg/s +
　stem:[\hat{L}_{a,i,n}]：ステップ stem:[n] からステップ stem:[n+1] における潜熱負荷に関する係数, kg/(s kg/kg(DA)) +
　stem:[\hat{L}_{b,i,n}]：ステップ stem:[n] からステップ stem:[n+1] における潜熱負荷に関する係数, kg/s +
である。

　式(b4)も同様に後退差分で離散化すると次式となる。

[stem]
++++
C_{lh,frt,i} \cdot \frac{ X_{frt,i,n+1} - X_{frt,i,n} }{ \Delta t }
= G_{lh,frt} \cdot ( X_{r,i,n+1} - X_{frt,i,n+1} )
\tag{b6}
++++

　式(b6)をステップ stem:[n+1] における室 stem:[i] の家具等の絶対湿度 stem:[X_{frt,i,n+1}] について解くと、

[stem]
++++
X_{frt,i,n+1} = \frac{ C_{lh,frt,i} \cdot X_{frt,i,n} + \Delta t \cdot G_{lh,frt} \cdot X_{r,i,n+1} }
{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} }
\tag{b7}
++++

となる。これを式(b5)に代入すると、

[stem]
++++
\begin{split}
\rho_a \cdot V_{room,i} \cdot \frac{ X_(r,i,n+1)-X_(r,i,n)}{Δt}
&= \rho_a \cdot \hat{V}_{out,vent,i,n} \cdot ( X_{o,n+1} - X_{r,i,n+1} ) \\
&+ G_{lh,frt,i} \cdot C_{lh,frt,i} \cdot \frac{ X_{frt,i,n} - X_{r,i,n+1} }{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} } \\
&+ \rho_a \cdot \sum_j^{J-1}{ \hat{V}_{int,vent,i,j,n} \cdot ( X_{r,j,n+1} - X_{r,i,n+1} ) } \\
&+ \hat{X}_{gen,i,n} + \hat{X}_{hum,i,n} + \hat{L}_{a,i,n} \cdot X_{r,i,n+1} + \hat{L}_{b,i,n}
\end{split}
\tag{b8}
++++

となる。ステップ stem:[n+1] における室 stem:[i] および室 stem:[j] の絶対湿度に解くと、

[stem]
++++
\begin{split}
(
& \rho_a \cdot ( \frac{ V_{room,i} }{ \Delta t } + \hat{V}_{out,vent,i,n} )
+ ( \frac{G_{lh,frt,i} \cdot C_{lh,frt,i} }{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} } ) - \hat{L}_{a,i,n} ) \cdot X_{r,i,n+1} \\
&- \rho_a \sum_j^{J-1}{ \hat{V}_{int,vent,i,j,n} \cdot ( X_{r,j,n+1} - X_{r,i,n+1} ) } \\
&= \rho_a \cdot \frac{ V_{room,i} }{ \Delta t } \cdot X_{r,i,n} + \rho_a \cdot \hat{V}_{out,vent,i,n} \cdot X_{o,n+1} \\
&+ ( \frac{ G_{lh,frt,i} \cdot C_{lh,frt,i} }{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} } ) \cdot X_{frt,i,n} \\
&+ \hat{X}_{gen,i,n} + \hat{X}_{hum,i,n} + \hat{L}_{b,i,n}
\end{split}
\tag{b9}
++++

となる。式(b9)は左辺に室 stem:[i] の絶対湿度と室 stem:[j] の絶対湿度がでてくる連立方程式であり、行列式で表すと

[stem]
++++
( \boldsymbol{BRMX}_n - \boldsymbol{\hat{L}}_{a,n} ) \cdot \boldsymbol{X}_{r,n+1}
=\boldsymbol{BRMC}_n + \boldsymbol{\hat{L}}_{b,n}
\tag{b10}
++++

となる。ここで、

[stem]
++++
\boldsymbol{BRMX}_n = diag( \rho_a ( \frac{V_{room,i} }{ \Delta t } + \hat{V}_{out,vent,i,n} ) + ( \frac{ G_{lh,frt,i} \cdot C_{lh,frt,i} }{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} } ))
- \rho_a \cdot \hat{V}_{int,vent,n}
\tag{b11}
++++

であり、

[stem]
++++
\boldsymbol{BRXC}_n =
\begin{pmatrix}
  BRXC_{0,n} \\
  \vdots \\
  BRXC_{I-1,n}
\end{pmatrix}
++++

[stem]
++++
\begin{split}
BRXC_{i,n} &= \rho_a \cdot \frac{ V_{room,i} }{ \Delta t } \cdot X_{r,i,n}
+ \rho_a \cdot \hat{V}_{out,vent,i,n} \cdot X_{o,n+1} \\
&+ ( \frac{G_{lh,frt,i} \cdot C_{lh,frt,i} }{ C_{lh,frt,i} + \Delta t \cdot G_{lh,frt} } ) \cdot X_{frt,i,n}
+ \hat{X}_{gen,i,n} + \hat{X}_{hum,i,n}
\end{split}
\tag{b12}
++++

[stem]
++++
\boldsymbol{\hat{L}}_{a,n} = diag( \hat{L}_{a,i,n} )
++++

[stem]
++++
\boldsymbol{\hat{L}}_{b,n} =
\begin{pmatrix}
  \hat{L}_{b,0,n} \\
  \vdots \\
  \hat{L}_{b,I-1,n}
\end{pmatrix}
++++

である。ここで、stem:[diag] は室の数を stem:[I] とすると、室 stem:[0] から stem:[I-1] の対角行列を表す。
stem:[\boldsymbol{\hat{V}}_{int,vent,n}] は室間換気を表す stem:[I \times I] の行列であり、例えば、室総数が3の場合で室1から室0へ60m^3^/sの換気量がある場合は、

[stem]
++++
\boldsymbol{\hat{V}}_{int,vent,n}
= \begin{pmatrix}
  -60 & 60 & 0 \\
  0   & 0  & 0 \\
  0   & 0  & 0
\end{pmatrix}
++++

となり、室総数が3の場合で室1から室0へ60m^3^/sの換気量かつ室2から室0へ30m^3^/sの換気量がある場合は、

[stem]
++++
\boldsymbol{\hat{V}}_{int,vent,n}
= \begin{pmatrix}
  -90 & 60 & 30 \\
  0   & 0  &  0 \\
  0   & 0  &  0
\end{pmatrix}
++++

となる。式で表すと、

[stem]
++++
\begin{split}
\boldsymbol{\hat{V}}_{int,vent,n}
&= - diag \left (
\sum_j^{J-1}{\hat{V}_{int,vent,0,j,n}} \  \cdots \  \sum_j^{J-1}{\hat{V}_{int,vent,i,j,n}} \  \dots \  \sum_j^{J-1}{\hat{V}_{int,vent,I-1,j,n}}
\right ) \\
&+ \begin{pmatrix}
0 & \cdots & \hat{V}_{int,vent,0,j,n} & \cdots & \hat{V}_{int,vent,0,J-1,n} \\
\vdots & \ddots & \vdots & & \vdots \\
\hat{V}_{int,vent,i,0,n} & \cdots & 0 & \cdots & \hat{V}_{int,vent,i,J-1,n} \\
\vdots & & \vdots & \ddots & \vdots \\
\hat{V}_{int,vent,I-1,0,n} & \cdots & \hat{V}_{int,vent,I-1,j,n} & \cdots & 0 \\
\end{pmatrix}
\end{split}
++++

となる。

ここで、 「目標とする絶対湿度を設定する場合」と「除湿・加湿量を設定する場合（除湿量・加湿量がゼロの場合も含む）」で式(b10)における未知数が異なる。
この式について、変数を指定する項目と指定しない項目とに分離すると、

[stem]
++++
\boldsymbol{BRMX}_n \cdot ( \boldsymbol{X'}_{r,n+1} + \boldsymbol{X}_{r,set,n+1} ) = \boldsymbol{BRMC}_n + \boldsymbol{\hat{L}}'_{L,n} + \boldsymbol{\hat{L}}_{L,set,n}
++++

となる。未知数を左辺に既知数を右辺に整理する。

[stem]
++++
\boldsymbol{BRMX}_n \cdot \boldsymbol{X'}_{r,n+1} - \boldsymbol{\hat{L}}'_{L,n}
= - \boldsymbol{BRMX}_n \cdot \boldsymbol{X}_{r,set,n+1} + \boldsymbol{BRMC}_n + \boldsymbol{\hat{L}}_{L,set,n}
++++

　ここで、

[stem]
++++
\boldsymbol{X'}_{r,n+1} = {\begin{pmatrix} X'_{r,0,n+1} & \cdots & X'_{r,i,n+1} & \cdots & X'_{r,I-1,n+1} \end{pmatrix}}^T
++++

[stem]
++++
\boldsymbol{\hat{L}'}_{L,n} = {\begin{pmatrix} \hat{L}'_{L,0,n} & \cdots & \hat{L}'_{L,i,n} & \cdots & \hat{L}'_{L,I-1,n} \end{pmatrix}}^T
++++

[stem]
++++
\boldsymbol{X}_{r,set,n+1} = {\begin{pmatrix} X_{r,set,0,n+1} & \cdots & X_{r,set,i,n+1} & \cdots & X_{r,set,I-1,n+1} \end{pmatrix}}^T
++++

[stem]
++++
\boldsymbol{\hat{L}}_{L,set,n} = {\begin{pmatrix} \hat{L}_{L,set,0,n} & \cdots & \hat{L}_{L,set,i,n} & \cdots & \hat{L}_{L,set,I-1,n} \end{pmatrix}}^T
++++

であり、 +
　stem:[X'_{r,i,n+1}]：ステップ stem:[n+1] における室iの絶対湿度（ただし、設定絶対湿度を定める場合は0とする）, kg/kg(DA) +
　stem:[\hat{L}'_{L,i,n}]：ステップ stem:[n] からステップ stem:[n+1] における室 stem:[i] の潜熱負荷（加湿を正・除湿を負とする）（ただし、設定絶対湿度を定めない場合は0とする）, kg/s +
　stem:[X_{r,set,i,n+1}]：ステップ stem:[n+1] における室iの設定絶対湿度（ただし、設定絶対湿度を定めない場合は0とする）, kg/kg(DA) +
　stem:[\hat{L}_{L,set,i,n}]：ステップ stem:[n] からステップ stem:[n+1] における室 stem:[i] の設定潜熱負荷（加湿を正・除湿を負とする）（ただし、設定絶対湿度を定める場合は0とする）, kg/s +
である。ここで、 stem:[X'_{r,i,n+1}] と stem:[\hat{L}'_{L,i,n}] のどちらか一方は必ず0となる。
同様に、stem:[X_{r,set,i,n+1}] と stem:[\hat{L}_{L,set,i,n}] のどちらか一方は必ず0となる。 +
　stem:[X'_{r,i,n+1}] と stem:[\hat{L}'_{L,i,n}] のどちらか一方は必ず0となることを利用し、

〖BRMK〗_n=[■(〖BRMK〗_(0,0,n)&⋯&〖BRMK〗_(0,j,n)&⋯&〖BRMK〗_(i,J-1,n)@⋮&⋱&⋮&&⋮@〖BRMK〗_(i,0,n)&⋯&〖BRMK〗_(i,j,n)&⋯&〖BRMK〗_(i,J-1,n)@⋮&&⋮&⋱&⋮@〖BRMK〗_(I-1,0,n)&⋯&〖BRMK〗_(I-1,j,n)&⋯&〖BRMK〗_(i-1,J-1,n) )]
BRMK_(i,j,n)=BRMX_(i,j)⋅f ̂_(set,j,n)-(1-f ̂_(set,j,n) )
とおくと、
〖BRMK〗_n⋅(X_(r,n+1)^'+L ̂_(L,n)^' )=-BRMX_n∙X_(r,set,n+1)+〖BRMC〗_n+L ̂_(L,set,n)
となり、
k_n=X_(r,n+1)^'+L ̂_(L,n)^'=〖BRMK〗_n^(-1)  (-BRMX_n∙X_(r,set,n+1)+〖BRMC〗_n+L ̂_(L,set,n) )
を解けばよい。ここで、f ̂_(set,j,n)は、室jにおいて、絶対湿度を指定する場合（加湿・除湿量は指定された室の絶対湿度を満たすように成り行きで定まる場合）を1、室の絶対湿度を指定せず成り行きの絶対湿度とする場合（加湿・除湿を行わない又は加湿・除湿を室の絶対湿度に依らず定められた量行う場合）を0とする。
また、
k_n=X_(r,n+1)^'+L ̂_(L,n)^'
における、室iにおける要素X_(r,i,n+1)^'またはL ̂_(L,i,n)^'について、どちらかは必ずゼロになるため、前述のf ̂_(set,i,n)（添字はiとした）を用いて、
X_(r,i,n+1)={■(k_(i,n)&(f ̂_(set,i,n)=0)@X_(r,set,i,n+1)&(f ̂_(set,i,n)=1) )┤
L ̂_(L,i,n)={■(L ̂_(L,set,i,n)&(f ̂_(set,i,n)=0)@k_(i,n)&(f ̂_(set,i,n)=1) )┤
と表すことができる。

② 除湿・加湿量を設定する場合（除湿量・加湿量がゼロの場合も含む）

(BRMX_n-L ̂_(a,n) )∙X_(r,n+1)=〖BRMC〗_n+L ̂_(b,n)

X_(r,n+1)=(BRMX_n-L ̂_(a,n) )^(-1)∙(〖BRMC〗_n+L ̂_(b,n) )

ア）除湿・加湿を行わない場合、
[stem]
++++
L ̂_(a,n)=0
++++
[stem]
++++
L ̂_(b,n)=0
++++
である。
イ）一定量の除湿・加湿を行う場合、
L ̂_(a,n)=0
L ̂_(b,n)=[■(L ̂_(L,const,0,n)@⋮@L ̂_(L,const,I-1,n) )]
である。ここで、
L ̂_(L,const,i,n)
：ステップnからステップn+1における室iの潜熱負荷（加湿を正・除湿を負とする）, kg/s
である。
ウ）室の絶対湿度に応じて一定量の除湿を行う場合
なお、室の絶対湿度に応じて加湿量が決まる機構をもつ設備は存在しないため、本パターンにおいては、除湿のみを考える。
X_(r,n+1)=(BRMX_n-L ̂_(a,n) )^(-1)∙(〖BRMC〗_n+L ̂_(b,n) )

を解き、負荷は、
L ̂_(L,n)=L ̂_(a,n)∙X_(r,n+1)+L ̂_(b,n)
となる。
ここで、L ̂_(a,n)とL ̂_(b,n)の決め方は設備固有のものである。
多くの場合、この方法は除湿を行う場合に採用される。熱交換器表面の飽和絶対湿度よりも室の絶対湿度が上回っている場合は除湿を行うが、下回っている場合は除湿が行われない。このように部屋の除湿の絶対湿度に依存して除湿の有無が決定される場合、まずは、L ̂_(L,n)を計算し、L ̂_(L,i,n)≥0の場合（この場合、除湿負荷を負としている）、除湿が行われないものとして、
[stem]
++++
L ̂_(a,i,n)=0
++++
[stem]
++++
L ̂_(b,i,n)=0
++++
として再計算する。
次に、L ̂_(a,n)とL ̂_(b,n)の決め方を記す。
ア）ルームエアコンディショナーの場合
室内機の吹き出し絶対湿度X_(RAC,out)は吸い込み湿度X_(RAC,in)と熱交換器表面の飽和絶対湿度X_(RAC,srf,ex)を用いて次のように表される。
[stem]
++++
X_(RAC,out)=BF∙X_(RAC,in)+(1-BF)∙X_(RAC,srf,ex)
(14)
++++
ここで、
X_(RAC,out)
	：ルームエアコンディショナーの室内機の吹き出し絶対湿度, kg/kg(DA)
X_(RAC,in)
	：ルームエアコンディショナーの室内機の吸い込み絶対湿度, kg/kg(DA)
X_(RAC,srf,ex)
	：ルームエアコンディショナーの室内機の熱交換器表面の絶対湿度, kg/kg(DA)
BF	：ルームエアコンディショナーのバイパスファクター
である。
ここで、ルームエアコンディショナーの吹き出し風量をV_RACとすると、除湿量は、
[stem]
++++
L_(L,i)=-V_RAC∙ρ_a∙(X_(RAC,in)-X_(RAC,out) )
(15)
++++
と表される。ここで、
V_RAC	：ルームエアコンディショナーの吹き出し風量, m3/s
である。
ルームエアコンディショナーの室内機の吸い込み絶対湿度X_(RAC,in)は室の絶対湿度X_rに等しいとし、式(15)に式(14)を代入すると、
[stem]
++++
L_L=-V_RAC∙ρ_a∙(X_(RAC,in)-X_(RAC,out) )
=-V_RAC∙ρ_a∙(X_(RAC,in)-(BF∙X_(RAC,in)+(1-BF)∙X_(RAC,srf,ex) ))
=-V_RAC∙ρ_a∙(1-BF)∙(X_r-X_(RAC,srf,ex) )
(16)
となる。
ここで、潜熱負荷L_Lを
L_L=L_a  X_r+L_b
と表したとすると、
L_a=-V_RAC∙ρ_a∙(1-BF)
L_b=V_RAC∙ρ_a∙(1-BF)∙X_(RAC,srf,ex)
となる。


++++




==== 1. 概要

室の温度バランス式を連立させて、次時刻の室の温度を計算する式を導出する。

==== 2. 記号説明

==== 3. 境界表面における熱収支

===== 1) 表面温度

ステップ stem:[n+1] における境界 stem:[j] の表面温度 stem:[\theta_{s,j,n+1}] は次式により表される。

[stem]
++++
\theta_{s,j,n+1}
= \phi_{A0,j} \cdot q_{j,n+1}
+ \sum_{m=1}^{M}{\theta'_{S,A,j,m,n+1}}
+ \phi_{T0,j} \cdot \theta_{rear,j,n+1}
+ \sum_{m=1}^{M}{\theta'_{S,T,j,m,n+1}}
\tag{3.1}
++++