:stem: latexmath

=== A. 「外皮の部位の面積等を用いずに外皮性能を評価する方法」を用いた場合の外皮の部位の面積や長さの推定

==== A.1 規模係数（テスト2）

　規模係数 stem:[r_{size}] は式(1)による。

[stem]
++++
r_{size} = \frac{A_{f,total}}{A_{s,f,total}} \tag{1}
++++

　ここで、 +
　stem:[r_{size}]：規模係数 +
　stem:[A_{f,total}]：床面積の合計, m^2^ +
　stem:[A_{s,f,total}]：簡易モデル住戸の床面積の合計, m^2^ +
である。ここで、簡易モデル住戸の床面積の合計stem:[A_{s,f,total}]は、90.0(m^2^)とする。

==== A.2 主開口方位
　主開口方位は南西とする。

==== A.3 一般部位
　一般部位の部位の種類・隣接空間の種類・方位・熱貫流率は表1による。面積は表1の値に規模係数を乗じた値とする。

表1 一般部位の種類・隣接空間の種類・方位・面積
[cols="^.^3,^.^3,^.^4,^.^3,^.^6,^.^6,^.^6,^.^6,^.^4"]
|=================================
.2+| 番号 .2+| 部位 +
の +
種類 .2+| 隣接空間 +
の +
種類 .2+| 方位^※1^ 4+| 面積(m^2^) .2+| 熱貫流率(W/m^2^K)
| 床断熱住戸 +
浴室床断熱^※2^
| 床断熱住戸 +
浴室基礎断熱^※3^
| 床断熱住戸 +
浴室床なし^※4^
| 基礎断熱住戸
| 1 | 屋根 +
又は +
天井 | 外気 |  上面 | 50.85 | 50.85 | 50.85 | 50.85 | stem:[U_{s,roof}]
| 2 | 壁 | 外気             |   0度 | 30.47 | 30.47 | 30.47 | 30.47 | stem:[U_{s,wall}]
| 3 | 壁 | 外気             |  90度 | 22.37 | 22.37 | 22.37 | 22.37 | stem:[U_{s,wall}]
| 4 | 壁 | 外気             | 180度 | 47.92 | 47.92 | 47.92 | 47.92 | stem:[U_{s,wall}]
| 5 | 壁 | 外気             | 270度 | 22.28 | 22.28 | 22.28 | 22.28 | stem:[U_{s,wall}]
| 6 | 床 | 外気に通じる床裏 |  下面 | 45.05 | 45.05 | 48.36 |  0.00 | stem:[U_{s,floor,other}]
| 7 | 床 | 外気に通じる床裏 |  下面 |  3.31 |  0.00 |  0.00 |  0.00 | stem:[U_{s,floor,bath}]
|=================================

※1 主開口方位からの時計回りの角度（単位：度）で表す。ただし、「上面」「下面」を除く。 +
※2 浴室部分の外皮を床とする場合 +
※3 浴室部分の外皮を土間床等の外周部の基礎とする場合 +
※4 外皮の部位として浴室の床が存在しない場合

　ここで、 +
　stem:[U_{s,roof}]：簡易モデル住戸における屋根又は天井の熱貫流率, W/m^2^K +
　stem:[U_{s,wall}]：簡易モデル住戸における壁の熱貫流率, W/m^2^K +
　stem:[U_{s,floor,other}]：簡易モデル住戸におけるその他の床の熱貫流率, W/m^2^K +
　stem:[U_{s,floor,bath}]：簡易モデル住戸における浴室の床の熱貫流率, W/m^2^K +
である。

==== A.4 大部分がガラスで構成される窓等の開口部

===== A.4.1 部位の仕様

　大部分がガラスで構成される窓等の開口部の隣接空間の種類・方位・熱貫流率・垂直面日射熱取得率は表2による。面積は表2の値に規模係数を乗じた値とする。

表2 大部分がガラスで構成される窓等の開口部の種類・隣接空間の種類・方位・面積
[cols="^.^2,^.^7,^.^4,^.^5,^.^8,^.^9"]
|=================================
| 番号 |	隣接空間の種類 | 方位^※1^ | 面積 (m^2^) | 熱貫流率(W/m^2^K) | 垂直面日射熱取得率
| 1 | 外気 | 0度 | 22.69 .4+| stem:[U_{s,window}] .4+| stem:[\eta_{s,d}]
| 2 | 外気 | 90度 | 2.38
| 3 | 外気 | 180度 | 3.63
| 4 | 外気 | 270度 | 4.37
|=================================

※1 主開口方位からの時計回りの角度（単位：度）で表す。ただし、「上面」「下面」を除く。

　ここで、 +
　stem:[U_{s,window}]：簡易モデル住戸における窓の熱貫流率, W/m^2^K +
　stem:[\eta_{s,d}]：簡易モデル住戸における垂直面日射熱取得率 +
である。また、

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
\eta_{s,d} = \frac{ ( \eta_{s,d,h} + \eta_{s,d,c} ) }{2}	\tag{2}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

である。ここで、 +
　stem:[\eta_{s,d,h}]：簡易モデル住戸における暖房期の垂直面日射熱取得率 +
　stem:[\eta_{s,d,c}]：簡易モデル住戸における冷房期の垂直面日射熱取得率 +
である。

　また、全ての大部分がガラスで構成される窓等の開口部において、日除け下端から窓上端までの垂直方向の距離stem:[y_1]は0mとし、窓の開口高さ寸法stem:[y_2]は1.1mとする。壁面から日除けの張り出し寸法stem:[z]は次項A.4.2に定める値とする。

===== A.4.2 壁面からの日除けの張り出し寸法

　壁面から日除けの張り出し寸法stem:[z]は式(3)による。 +
（この式は、もう少しきちんと考察する必要がある。（特に（3a）））

1地域～7地域

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z = \frac{z_h + z_c }{ 2 }	\tag{3a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

8地域

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z = z_c \tag{3b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

　ここで、 +
　stem:[z]：壁面から日除けの張り出し寸法, m +
　stem:[z_h]：暖房期の壁面から日除けの張り出し寸法, m +
　stem:[z_c]：冷房期の壁面から日除けの張り出し寸法, m +
である。

　暖房期及び冷房期の壁面から日除けの張り出し寸法stem:[z_h]・stem:[z_c]は、暖房期及び冷房期の取得日射熱補正係数を指定する場合は次の(1)により、指定しない場合は(2)による。

====== (1) 取得日射熱補正係数を指定する場合

stem:[\frac{f_{s,h}}{0.01} - a_h \le 0]の場合

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_h = 5.0 \tag{4a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

stem:[\frac{f_{s,h}}{0.01} - a_h \gt 0]の場合

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_h= \left\{ \begin{array}{ll}
  b_h ( c_h y_1 + y_2 ) / ( \frac{f_{s,h} }{0.01} - a_h ) & ( f_{s,h} \le 0.72 ) \\
  b_h ( c_h y_1 + y_2 ) / ( \frac{0.72}{0.01} - a_h ) & ( f_{s,h} \gt 0.72 )
\end{array} \right.
\tag{4b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

　ただし、stem:[z_h]が5.0を超える場合はstem:[z_h=5.0]とする。

stem:[\frac{f_{s,c}}{0.01} - a_c \le 0]の場合

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_c = 5.0	\tag{4c}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

stem:[\frac{f_{s,c}}{0.01} - a_c \gt 0]の場合

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_c = \left\{ \begin{array}{ll}
  b_c ( c_c y_1 + y_2 ) / ( \frac{f_{s,c} }{0.01} - a_c ) & ( f_{s,c} \le 0.93 ) \\
  b_c ( c_c y_1 + y_2 ) / ( \frac{0.93}{0.01} - a_c ) & ( f_{s,c} \gt 0.93 )
\end{array} \right.
\tag{4d}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

　ここで、 +
　stem:[z_h]：暖房期の壁面から日除けの張り出し寸法, m +
　stem:[z_c]：冷房期の壁面から日除けの張り出し寸法, m +
　stem:[y_1]：日除け下端から窓上端までの垂直方向の距離(stem:[=0.0]), m +
　stem:[y_2]：窓の開口高さ寸法(stem:[=1.1]), m +
　stem:[f_{s,h}]：簡易モデル住戸における暖房期の取得日射熱補正係数 +
　stem:[f_{s,c}]：簡易モデル住戸における冷房期の取得日射熱補正係数 +
である。

　式(4)における係数stem:[a_h]・stem:[b_h]・stem:[c_h]及びstem:[a_c]・stem:[b_c]・stem:[c_c]は、暖房期・冷房期の別・地域の区分・方位に応じて表3(a)及び表3(b)に与えられる。

表3(a)  式(4)における係数stem:[a_h]・stem:[b_h]・stem:[c_h]
[cols="^.^5,^.^9,^.^3,^.^3,^.^3"]
|=================================
| 地域の区分 | 方位 | stem:[a_h] | stem:[b_h] | stem:[c_h]
.2+| 1～7地域 | 南東・南・南西 | 5 | 20 | 3
| 南東・南・南西以外 | 10 | 15 | 2
|=================================

表3(b)  式(4)における係数stem:[a_c]・stem:[b_c]・stem:[c_c]
[cols="^.^5,^.^9,^.^3,^.^3,^.^3"]
|=================================
| 地域の区分 | 方位 | stem:[a_c] | stem:[b_c] | stem:[c_c]
.2+| 1～7地域 | 南 | 24 | 9 | 3
| 南以外 | 16 | 24 | 2
.2+| 8地域 | 南東・南・南西 | 16 | 19 | 2
| 南東・南・南西以外 | 16 | 24 | 2
|=================================

====== (2) 取得日射熱補正係数を指定しない場合

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_h = \frac{ ( y_1 + y_2 ) }{ l_{h,2} } \tag{5a}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
z_c = 0 \tag{5b}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

　ここで、 +
　stem:[z_h]：暖房期の壁面から日除けの張り出し寸法, m +
　stem:[z_c]：冷房期の壁面から日除けの張り出し寸法, m +
　stem:[y_1]：日除け下端から窓上端までの垂直方向の距離(stem:[=0.0]), m +
　stem:[y_2]：窓の開口高さ寸法(stem:[=1.1]), m +
である。また、

[stem]
++++++++++++++++++++++++++++++++++++++++++++
\begin{equation}
l_{h,2} = \frac{1}{0.3} \tag{6}
\end{equation}
++++++++++++++++++++++++++++++++++++++++++++

とする。

==== A.5 大部分がガラスで構成されないドア等の開口部

　大部分がガラスで構成されないドア等の開口部の隣接空間の種類・方位・熱貫流率は表4による。面積は表4の値に規模係数を乗じた値とする。

表4 大部分がガラスで構成されないドア等の開口部
[cols="^.^2,^.^5,^.^4,^.^5,^.^7"]
|=================================
| 番号 | 隣接空間の +
種類 | 方位^※1^ | 面積(m^2^) | 熱貫流率(W/m^2^K)
| 1 | 外気 | 90度 | 1.89 .2+| stem:[U_{s,door}]
| 2 | 外気 | 180度 | 1.62
|=================================

※1 主開口方位からの時計回りの角度（単位：度）で表す。ただし、「上面」「下面」を除く。

　ここで、 +
　stem:[U_{s,door}]：簡易モデル住戸におけるドアの熱貫流率, W/m^2^K +
である。

==== A.6 土間床等の外周部

　土間床等の外周部の部位の種類・隣接空間の種類・方位・熱貫流率は表5による。面積は表5の値に規模係数を乗じた値とする。

表5 一般部位の種類・隣接空間の種類・方位・面積
[cols="^.^2,^.^8,^.^4,^.^5,^.^5,^.^5,^.^5,^.^5"]
|=================================
.2+| 番号 .2+| 隣接空間の種類 .2+| 方位^※1^ +
（参考） 4+| 長さ(m) .2+| 熱貫流率(W/mK)
| 床断熱住戸 +
浴室床断熱^※2^
| 床断熱住戸 +
浴室基礎断熱^※3^
| 床断熱住戸 +
浴室床なし^※4^
| 基礎断熱住戸
| 1 | 外気 | 90度 4+| 1.82 .3+| stem:[ψ_{s,prm,etrc}]
| 2 | 外気 | 180度 4+| 1.37
| 3 | 外気に通じる床裏 | － | 3.19 | 3.19 | 3.19 | 0.0
| 4 | 外気 | 90度 | 0.0 | 1.82 | 0.0 | 1.82 .3+| stem:[ψ_{s,prm,bath}]
| 5 | 外気 | 180度 | 0.0 | 1.82 | 0.0 | 1.82
| 6 | 外気に通じる床裏 | － | 0.0 | 3.64 | 0.0 | 0.0
| 7 | 外気 | 0度 | 0.0 | 0.0 | 0.0 | 10.61 .3+| stem:[ψ_{s,prm,other}]
| 8 | 外気 | 90度 | 0.0 | 0.0 | 0.0 | 1.15
| 9 | 外気 | 180度 | 0.0 | 0.0 | 0.0 | 7.42
| 10 | 外気 | 270度 | 0.0 | 0.0 | 0.0 | 4.79
|=================================

※1 主開口方位からの時計回りの角度（単位：度）で表す。ただし、「上面」「下面」を除く。 +
※2 浴室部分の外皮を床とする場合 +
※3 浴室部分の外皮を土間床等の外周部の基礎とする場合 +
※4 外皮の部位として浴室の床が存在しない場合

　ここで、 +
　stem:[ψ_{s,prm,etrc}]：簡易モデル住戸における玄関等の土間床等の外周部の線熱貫流率, W/mK +
　stem:[ψ_{s,prm,bath}]：簡易モデル住戸における浴室の土間床等の外周部の線熱貫流率, W/mK +
　stem:[ψ_{s,prm,other}]：簡易モデル住戸におけるその他の土間床等の外周部の線熱貫流率, W/mK +
である。

==== A.7 土間床等の中心部

　土間床等の中心部の面積は表6による。面積は表6の値に規模係数を乗じた値とする。

表6 土間床等の中心部の面積

[cols="^.^2,^.^5,^.^5,^.^5,^.^5"]
|=================================
.2+| 番号 4+| 面積(m^2^)
| 床断熱住戸 +
浴室床断熱^※1^
| 床断熱住戸 +
浴室基礎断熱^※2^
| 床断熱住戸 +
浴室床なし^※3^
| 基礎断熱住戸
| 1 4+| 2.48
| 2 | 0.00 | 3.31 | 0.00 | 3.31
| 3 | 0.00 | 0.00 | 0.00 | 45.05
|=================================

※1 浴室部分の外皮を床とする場合 +
※2 浴室部分の外皮を土間床等の外周部の基礎とする場合 +
※3 外皮の部位として浴室の床が存在しない場合
