from dataclasses import dataclass


@dataclass
class InputScheduleElement:
    """List of schedules.

    Shcedule consits of 7 types as below;
        number of people
        heat generated from appliances, W
        heat generated from lighting, W / m2
        heat generated by cooking, W
        vapor generated by cooking, g / h
        local ventiration amount, m3 / h
        air conditioning mode, (0, 1, 2, 3...) which is defined in common tag.

    NOTES:
        Schedule consits of 7 types. 
    """

    number_of_people: list[float]
    heat_generation_appliances: list[float]
    heat_generation_lighting: list[float]
    heat_generation_cooking: list[float]
    vapor_generation_cooking: list[float]
    local_vent_amount: list[float]
    is_temp_limit_set: list[int]
    d: dict



    @classmethod
    def read(cls, id: int, d: dict):

        def read_each(tag: str, arg_type: str):

            if tag in d:

                ds = d[tag]

                if len(ds) not in [1, 24, 48, 96]:

                    raise ValueError(f'The length of the list should be 1, 24, 48, or 96 for \'{tag}\' in \'schedule\' tag. (ID={id})')

                try:

                    match arg_type:

                        case 'float':
                            return [float(d) for d in ds]
                        case 'int':
                            return [int(d) for d in ds]
                        case _:
                            raise Exception()
                    
                except:

                    raise ValueError(f'An invalid value was specified for \'{tag}\' in \'schedule\' tag. (ID={id})')

                #return get_value(s=tag, ds=ds, arg_type=arg_type)
            
            else:

                match arg_type:
                    case 'float':
                        return [0.0]
                    case 'int':
                        return [0]
                    case _:
                        raise Exception()

        number_of_people = read_each(tag='number_of_people', arg_type='float')
        heat_generation_appliances = read_each(tag='heat_generation_appliances', arg_type='float')
        heat_generation_lighting = read_each(tag='heat_generation_lighting', arg_type='float')
        heat_generation_cooking = read_each(tag='heat_generation_cooking', arg_type='float')
        vapor_generation_cooking= read_each(tag='vapor_generation_cooking', arg_type='float')
        local_vent_amount = read_each(tag='local_vent_amount', arg_type='float')
        is_temp_limit_set = read_each(tag='is_temp_limit_set', arg_type='int')
        
        return InputScheduleElement(
            number_of_people=number_of_people,
            heat_generation_appliances=heat_generation_appliances,
            heat_generation_lighting=heat_generation_lighting,
            heat_generation_cooking=heat_generation_cooking,
            vapor_generation_cooking=vapor_generation_cooking,
            local_vent_amount=local_vent_amount,
            is_temp_limit_set=is_temp_limit_set,
            d=d
        )

